---
- hosts: all
  sudo: yes
  vars_files:
    - vars/common.yml
  roles:
    - common

- hosts: loadbalancers
  sudo: yes
  roles:
    - haproxy

- hosts: appservers
  sudo: yes
  vars_files:
    - vars/common.yml
  roles:
    - ruby
    - rails
    - nginx-passenger
    - deploy-conf

- hosts: dbservers
  sudo: yes
  vars_files:
    - vars/common.yml
  roles:
    #- ruby
    - postgres